# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at midnight daily
    - cron: '0 0 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d '' -s ${{ secrets.NETLIFY_BUILD_HOOK }}
